name: bible_book_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.2.0
  flutter_statusbarcolor_ns: ^0.5.0
  fluttertoast: ^8.2.4
  get: 4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  image: ^4.1.7
  interactive_bottom_sheet: ^1.0.0
  line_icons: ^2.0.3
  loading_overlay: ^0.3.0
  logger: ^2.1.0
  lottie: ^2.7.0
  path: ^1.8.3
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sizer: ^2.0.15
  sqflite: ^2.3.0
  store_redirect: ^2.0.1
  url_launcher: ^6.2.4

dependency_overrides:
  # for dio_http_cache
  json_serializable: ^6.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/db/
    - assets/lotties/
  fonts:
    - family: Abyssinica
      fonts:
        - asset: assets/fonts/AbyssinicaSIL-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/bible_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/images/bible_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/bible_icon.png"
